insert into public.catalog_versions (
  id,
  version_key,
  status,
  summary,
  internal_notes,
  published_at
) values (
  '11111111-1111-4111-8111-111111111111',
  'mvp-catalog-2026-05',
  'published',
  'MVP starter catalog for France skincare routine generation.',
  'Seeded for local and staging smoke tests.',
  '2026-05-19T00:00:00Z'
) on conflict (version_key) do update set
  status = excluded.status,
  summary = excluded.summary,
  internal_notes = excluded.internal_notes,
  published_at = excluded.published_at;

insert into public.rule_versions (
  id,
  version_key,
  status,
  summary,
  internal_notes,
  published_at
) values (
  '22222222-2222-4222-8222-222222222222',
  'mvp-rules-2026-05',
  'published',
  'MVP recommendation rules for simple cleanse, hydrate, protect routines.',
  'Seeded for local and staging smoke tests.',
  '2026-05-19T00:00:00Z'
) on conflict (version_key) do update set
  status = excluded.status,
  summary = excluded.summary,
  internal_notes = excluded.internal_notes,
  published_at = excluded.published_at;

insert into public.catalog_products (
  id,
  brand_name,
  product_name,
  product_category,
  routine_step,
  inci_list,
  key_ingredients,
  function_tags,
  caution_tags,
  verified_claims,
  price_amount_minor,
  price_currency,
  price_band,
  size_value,
  size_unit,
  cost_per_unit_amount_minor,
  cost_per_unit_unit,
  market,
  availability_status,
  retailer_name,
  product_url,
  source_url,
  last_verified_at,
  next_review_at,
  formula_status,
  formula_changed_at,
  data_freshness_status,
  data_freshness_notes,
  publication_status,
  published_at,
  unpublished_at,
  review_flagged_at,
  review_reason
) values
(
  '33333333-3333-4333-8333-333333333333',
  'Routinelle Lab',
  'Soft Balance Cleanser',
  'cleanser',
  'cleanse',
  array['Aqua', 'Glycerin', 'Coco-Glucoside', 'Citric Acid'],
  array['Glycerin'],
  array['gentle', 'hydrating'],
  array[]::text[],
  '[{"claim":"Gentle cosmetic cleanser","sourceName":"MVP seed","verifiedAt":"2026-05-19T00:00:00Z"}]'::jsonb,
  950,
  'EUR',
  'low',
  150,
  'ml',
  6,
  'ml',
  'france',
  'available',
  'Seed Retailer',
  'https://example.com/routinelle-soft-balance-cleanser',
  'https://example.com/routinelle-soft-balance-cleanser',
  '2026-05-19T00:00:00Z',
  '2026-11-19T00:00:00Z',
  'stable',
  null,
  'current',
  null,
  'published',
  '2026-05-19T00:00:00Z',
  null,
  null,
  null
),
(
  '44444444-4444-4444-8444-444444444444',
  'Routinelle Lab',
  'Barrier Comfort Cream',
  'moisturizer',
  'hydrate',
  array['Aqua', 'Glycerin', 'Squalane', 'Ceramide NP', 'Panthenol'],
  array['Glycerin', 'Squalane', 'Ceramide NP', 'Panthenol'],
  array['hydrating', 'barrier-support', 'gentle'],
  array[]::text[],
  '[{"claim":"Cosmetic hydration and comfort support","sourceName":"MVP seed","verifiedAt":"2026-05-19T00:00:00Z"}]'::jsonb,
  1590,
  'EUR',
  'moderate',
  50,
  'ml',
  32,
  'ml',
  'france',
  'available',
  'Seed Retailer',
  'https://example.com/routinelle-barrier-comfort-cream',
  'https://example.com/routinelle-barrier-comfort-cream',
  '2026-05-19T00:00:00Z',
  '2026-11-19T00:00:00Z',
  'stable',
  null,
  'current',
  null,
  'published',
  '2026-05-19T00:00:00Z',
  null,
  null,
  null
),
(
  '55555555-5555-4555-8555-555555555555',
  'Routinelle Lab',
  'Daily Mineral SPF',
  'sunscreen',
  'protect',
  array['Aqua', 'Zinc Oxide', 'Glycerin', 'Caprylic/Capric Triglyceride'],
  array['Zinc Oxide', 'Glycerin'],
  array['uv-support', 'gentle'],
  array[]::text[],
  '[{"claim":"Daily cosmetic UV protection support","sourceName":"MVP seed","verifiedAt":"2026-05-19T00:00:00Z"}]'::jsonb,
  1890,
  'EUR',
  'moderate',
  50,
  'ml',
  38,
  'ml',
  'france',
  'available',
  'Seed Retailer',
  'https://example.com/routinelle-daily-mineral-spf',
  'https://example.com/routinelle-daily-mineral-spf',
  '2026-05-19T00:00:00Z',
  '2026-11-19T00:00:00Z',
  'stable',
  null,
  'current',
  null,
  'published',
  '2026-05-19T00:00:00Z',
  null,
  null,
  null
),
(
  '66666666-6666-4666-8666-666666666666',
  'Routinelle Lab',
  'Oil Balance Support Serum',
  'serum',
  'support',
  array['Aqua', 'Niacinamide', 'Zinc PCA', 'Glycerin'],
  array['Niacinamide', 'Zinc PCA', 'Glycerin'],
  array['oiliness', 'blemish-support', 'hydrating'],
  array['active-caution'],
  '[{"claim":"Cosmetic oiliness support","sourceName":"MVP seed","verifiedAt":"2026-05-19T00:00:00Z"}]'::jsonb,
  1490,
  'EUR',
  'moderate',
  30,
  'ml',
  50,
  'ml',
  'france',
  'available',
  'Seed Retailer',
  'https://example.com/routinelle-oil-balance-support-serum',
  'https://example.com/routinelle-oil-balance-support-serum',
  '2026-05-19T00:00:00Z',
  '2026-11-19T00:00:00Z',
  'stable',
  null,
  'current',
  null,
  'published',
  '2026-05-19T00:00:00Z',
  null,
  null,
  null
)
on conflict (brand_name, product_name, market) do update set
  product_category = excluded.product_category,
  routine_step = excluded.routine_step,
  inci_list = excluded.inci_list,
  key_ingredients = excluded.key_ingredients,
  function_tags = excluded.function_tags,
  caution_tags = excluded.caution_tags,
  verified_claims = excluded.verified_claims,
  price_amount_minor = excluded.price_amount_minor,
  price_currency = excluded.price_currency,
  price_band = excluded.price_band,
  size_value = excluded.size_value,
  size_unit = excluded.size_unit,
  cost_per_unit_amount_minor = excluded.cost_per_unit_amount_minor,
  cost_per_unit_unit = excluded.cost_per_unit_unit,
  availability_status = excluded.availability_status,
  retailer_name = excluded.retailer_name,
  product_url = excluded.product_url,
  source_url = excluded.source_url,
  last_verified_at = excluded.last_verified_at,
  next_review_at = excluded.next_review_at,
  formula_status = excluded.formula_status,
  formula_changed_at = excluded.formula_changed_at,
  data_freshness_status = excluded.data_freshness_status,
  data_freshness_notes = excluded.data_freshness_notes,
  publication_status = excluded.publication_status,
  published_at = excluded.published_at,
  unpublished_at = excluded.unpublished_at,
  review_flagged_at = excluded.review_flagged_at,
  review_reason = excluded.review_reason;
