import type { SkinConcern, SkinType } from "@/lib/domain/skin-profile";

export type PhotoAnalysisOutcome =
  | "analyzed"
  | "no_face_detected"
  | "needs_professional_care"
  | "unsupported_image"
  | "declined";

export type PhotoAnalysisResult = {
  outcome: PhotoAnalysisOutcome;
  skinType?: SkinType;
  concerns?: SkinConcern[];
  message: string;
};

/**
 * All user-facing copy for this feature is authored here, by Routinelle --
 * never generated by the model. The model's own output is fully
 * enum-constrained (one outcome, one skinType, up to three concerns), so
 * there is no AI-generated prose anywhere in the response surface that would
 * need to pass through claim-guardrails.ts's isApprovedCosmeticCopy.
 */
export const PHOTO_ANALYSIS_OUTCOME_MESSAGES: Record<PhotoAnalysisOutcome, string> = {
  analyzed:
    "Based on your photo, here's a suggested skin type and starting concerns. Feel free to change either before continuing.",
  no_face_detected:
    "We couldn't find a clear face in that photo. You can try another photo, or just answer the questions instead.",
  needs_professional_care:
    "Based on your photo, we'd recommend checking with a dermatologist or doctor before focusing on cosmetic routine changes. This isn't a diagnosis -- just a suggestion to have it looked at. You can still continue with the questions below.",
  unsupported_image:
    "We couldn't use that photo. You can try a different one, or just answer the questions instead.",
  declined:
    "Photo analysis isn't available for that photo right now. You can try another one, or just answer the questions instead.",
};
